Repository replicatedhq/replicated-lib, pull requests merged in 2024-05, with the labels that each got.

#43 fix: node 20 hangs if reponse body is not read
  dist/channels.js
  dist/clusters.js
  dist/customers.js
  dist/releases.js
  package.json
  src/channels.ts
  src/clusters.ts
  src/customers.ts
  src/releases.ts
Labels: bug::normal, type::bug

#44 feat(cmx): cluster port expose wildcards
  dist/clusters.d.ts
  dist/clusters.js
  dist/clusters.spec.js
  examples/expose-port.ts
  package-lock.json
  package.json
  src/clusters.spec.ts
  src/clusters.ts
Labels: type::feature

#45 fix(cmx): delete cluster wrong error code
  dist/clusters.js
  package-lock.json
  package.json
  src/clusters.ts
Labels: bug::regression, type::bug

#47 fix: requests hang, discard response body
  dist/applications.js
  dist/channels.js
  dist/clusters.js
  dist/customers.js
  dist/releases.js
  package-lock.json
  package.json
  src/applications.ts
  src/channels.ts
  src/clusters.ts
  src/customers.ts
  src/releases.ts
Labels: bug::normal, type::bug

#48 Joshd/sc 90798/gh actions automate release process
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  dist/applications.d.ts
  dist/applications.js
  dist/applications.spec.d.ts
  dist/applications.spec.js
  dist/channels.d.ts
  dist/channels.js
  dist/channels.spec.d.ts
  dist/channels.spec.js
  dist/clusters.d.ts
  dist/clusters.js
  dist/clusters.spec.d.ts
  dist/clusters.spec.js
  dist/configuration.d.ts
  dist/configuration.js
  dist/customers.d.ts
  dist/customers.js
  dist/customers.spec.d.ts
  dist/customers.spec.js
  dist/index.d.ts
  dist/index.js
  dist/releases.d.ts
  dist/releases.js
  dist/releases.spec.d.ts
  dist/releases.spec.js
  package-lock.json
  package.json
  pacts/npm_consumer-vp_service.json
  src/clusters.spec.ts
  src/releases.spec.ts
Labels: type::chore

#46 Adding ip family
  src/clusters.ts
  src/releases.ts
Labels: type::feature

#49 fix npm version
  .github/workflows/release.yml
Labels: type::chore
